services:
  - type: web
    name: ragchatbot-groww
    runtime: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run code/ui/app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.19