services:
  - type: web
    name: ragchatbot-groww
    runtime: python
    plan: standard
    buildCommand: pip install -r requirements.txt
    startCommand: python -m streamlit run code/ui/app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9